services:
    app:
        container_name: mailer-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
            - "8001:8001"
        volumes:
            - ./:/var/www/html
        networks:
            - lion

    mailhog:
        image: mailhog/mailhog
        container_name: mailer-mailhog
        restart: unless-stopped
        ports:
            - "8025:8025"
            - "1025:1025"
        networks:
            - lion

networks:
    lion:
